import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

import {Outfit} from "next/font/google"

const outfit = Outfit({ subsets: ["latin"], weight:["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Avion",
  description: "Generated by M Suleman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={outfit.className}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
